#!/usr/bin/env bash

# By [Awaxx] (d/m/y) 10/06/2022 

# - run
# - unpack

[[ -f ${1} ]] && { echo "This file exists."; exit 1; }
[[ -f ${2} ]] || { echo "Not a file."; exit 1; }
[[ ${3} ]] || { echo "No procedure provided."; exit 1; }

function main()
{
  local _runfile=${1}.run
  local _filepath=${2}
  local _filename=(${_filepath%/}); _filename=${_filename##*/}

  cat > $_runfile <<EOF
#!/usr/bin/env bash

$(cat ./header.txt)

_filecontent="$(hexdump -v -e '1/1 "\\x%02X"' $_filepath)"
_filename=$_filename

echo -ne \$_filecontent > /tmp/\$_filename

$([[ ${3} == "run" ]] && cat ./install.txt; [[ ${3} == "unpack" ]] && cat ./unpack.txt)

# - send yourself a thumb up
# wget|curl|devtcp http://installdmyapps.com

$(cat ./footer.txt)
EOF
}

main $@
exit 0