#!/usr/bin/env bash

# By [Awaxx] (d/m/y) 10/06/2022 

# mkrun <vendor_name> <file_include> <procedure_name>
# <vendor_name> will be ./vendor_name.run
# <file_include> is the file you wish to include for installation
# <procedure_name> run|unpack which you can tweak directly inside *.txt files
# you need to check procedure by hand for installation through the *.txt
# Contact Support: 555-911-911 RobCo Industries. :)
# Have fun.


[[ -f ${1} ]] && { echo "This file exists."; exit 1; }
[[ -f ${2} ]] || { echo "Not a file."; exit 1; }
[[ ${3} ]] || { echo "No procedure provided."; exit 1; }

function main()
{
  local _runfile=${1}.run
  local _filepath=${2}
  local _filename=${_filepath%/}; _filename=${_filename##*/}

  cat > $_runfile <<EOF
#!/usr/bin/env bash

$(cat ./header.txt)

_filename=$_filename
_filecontent="$(hexdump -v -e '1/1 "\\x%02X"' $_filepath)"

echo -ne \$_filecontent > /tmp/\$_filename

$([[ ${3} == "run" ]] && cat ./run.txt; [[ ${3} == "unpack" ]] && cat ./unpack.txt)

# - send yourself a thumb up
# wget|curl|devtcp http://installdmyapps.com

$(cat ./footer.txt)
EOF
}

main $@
exit 0
